modify the project status with mutt2task project

diff --git a/mutt2task b/mutt2task
--- a/mutt2task
+++ b/mutt2task
@@ -52,6 +52,16 @@ case "$1" in
 		task_find all
 		exit 1
 		;;
+	"project")
+		printf "Project: "
+		read project 0>&2
+		if [ "$project" ]; then
+			if ! task "$message_id" modify project:"$project"; then
+				echo "Can't change the project for $message_id"
+			fi
+		fi
+		exit 1
+		;;
 	*)
 		;;
 esac
